apiVersion: v1
items:
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:deployers
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: {{ .Release.Namespace }}
  userNames:
  - system:serviceaccount:{{ .Release.Namespace }}:deployer
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: {{ .Release.Namespace }}
  userNames:
  - system:serviceaccount:{{ .Release.Namespace }}:builder
- apiVersion: authorization.openshift.io/v1
  groupNames:
  - system:serviceaccounts:{{ .Release.Namespace }}
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:{{ .Release.Namespace }}
  userNames: null
kind: List
metadata: {}